### ISSUE TITLE
ValueError: invalid literal for int() with base 10 on second iteration

### ISSUE THREAD

**Issue by cwwmbm** [pgalko/Next-Number-Prediction#1]
Running everything as is, only added my openai api key. Running on the same dataset as in repository.

Full trace:
Iteration:1
Actual:332-Predicted:337. Tokens_Used:75
Iteration:2
Traceback (most recent call last):
  File "/Users/andreypopov/Documents/GitHub/Next-Number-Prediction/next_seq_nr.py", line 152, in <module>
    elif abs(int(next_nr)-predictions[i])/predictions[i] < 0.015:
ValueError: invalid literal for int() with base 10: 'The next number in the sequence [342 325 336 335 332] is 341.'

If relevant, I'm on Mac M1 Mini.

**Comment by cwwmbm** [comment]
Upon further investigation it would appear that Open AI API returns something that's a whole string as opposed to being just a number on second iteration. I added prin("Printing next_nr" + next_nr) just to see what comes back and the following did:
Iteration:1
Printing next_nr: 337
Actual:332-Predicted:337. Tokens_Used:75
Iteration:2
Printing next_nr: The next number in the sequence [342 325 336 335 332] is 341.

It would appear that a prompt modification is needed, I modified the following prompt: 'Incorrect. The number that follows {} is {}. Now try with a new sequence:{}.' to be 'Incorrect. The number that follows {} is {}. Now try with a new sequence:{}. Return number only'. and that fixed the issue.

I don't know how to do pull requests so can't submit this, but hopefully this will help others.

**Comment by pgalko** [comment]
Hi @cwwmbm, Thanks for contributing.
I have observed this error couple of times and it is related to LLM responding with a full sentence rather than a single number. So you are absolutely correct.
I will test it when the error pops up again and update the repo.
